### ISSUE TITLE
Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by BitTheByte** [facebook/sapp#54]
Error while reading issues with the following description
```
User input flows into WebView load: Values from user-controlled source may eventually flow into a Webview load potentially causing XSS
```

```
sapp --database-name=sapp.db server --source-directory=src/main/java
# Python 3.8.10
# Ubuntu 20.01
# Installed Using: pip install mariana-trench
```

```javascript
function adjustRange(range: Range, lines: $ReadOnlyArray<string>): Range {
  // TODO(T78595608): workaround for inaccurate Pysa locations with leading and
  // trailing whitespaces.

  // Assuming all ranges are single line.
  const source = lines[range.from.line].slice(range.from.ch, range.to.ch); // <<<<< ERROR
  const leadingWhitespace = source.search(/\S/);
  const trailingWhitespace = source.length - source.trimEnd().length;
  return {
    from: {
      line: range.from.line,
      ch: range.from.ch + leadingWhitespace,
    },
    to: {
      line: range.to.line,
      ch: range.to.ch - trailingWhitespace,
    },
  };
}
```

```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'slice')
    at Source.js:40
    at Source.js:80
    at Array.map (<anonymous>)
    at te (Source.js:63)
    at ne (Source.js:183)
    at $i (react-dom.production.min.js:153)
    at Ia (react-dom.production.min.js:175)
    at mc (react-dom.production.min.js:263)
    at ls (react-dom.production.min.js:246)
    at cs (react-dom.production.min.js:246)
```

**Comment by abishekvashok** [comment]
@serrapa can you try again after updating both sapp and Mariana trench, re-run Mariana trench, re injest the results to a new db, and see if the UI is functioning?

I think I made a fix by not rendering the flow and showing flow not available warning incase we find something outrageous like line numbers being -5s.

**Comment by serrapa** [comment]
Hello @abishekvashok,sorry for the late reply. With a new db I don't have any problem. Thank you.

**Comment by serrapa** [comment]
Hello @abishekvashok, I have just had the same problem with a clean database. I attached it here together with the APK and its decompiled code (it's inside `Ovaa/app/src/main/java`)
[Archive.zip](https://github.com/facebook/sapp/files/10726713/Archive.zip)
[sapp.db.zip](https://github.com/facebook/sapp/files/10726682/sapp.db.zip)

Once I click on the **traces** button in the UI, the window becomes white and the following errors appear in the console:
````
TypeError: Cannot read properties of undefined (reading 'slice')              react-dom.production.min.js:209 
    at Source.js:53:41
    at Source.js:93:12
    at Array.map (<anonymous>)
    at ce (Source.js:76:27)
    at ue (Source.js:204:21)
    at $i (react-dom.production.min.js:153:146)
    at Ia (react-dom.production.min.js:175:309)
    at mc (react-dom.production.min.js:263:406)
    at ls (react-dom.production.min.js:246:265)
    at cs (react-dom.production.min.js:246:194)
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'slice')           Source.js:53 
    at Source.js:53:41
    at Source.js:93:12
    at Array.map (<anonymous>)
    at ce (Source.js:76:27)
    at ue (Source.js:204:21)
    at $i (react-dom.production.min.js:153:146)
    at Ia (react-dom.production.min.js:175:309)
    at mc (react-dom.production.min.js:263:406)
    at ls (react-dom.production.min.js:246:265)
    at cs (react-dom.production.min.js:246:194)
````

**Comment by abishekvashok** [comment]
Will take a look.
