### ISSUE TITLE
Failed to parse the result of Mariana-trench

### ISSUE THREAD

**Issue by N1rv0us** [facebook/sapp#72]
## What's the Problem

I found Mariana-trench support "field" type sources/sinks : https://mariana-tren.ch/docs/models/#field-models
I tried to use this feature. and I catch an error when I use sapp to show the result. as follow:

```
Traceback (most recent call last):
  File "/Users/listennter/.venvs/dev-mariana/bin/sapp", line 8, in <module>
    sys.exit(cli())
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/cli_lib.py", line 207, in analyze
    pipeline.run(analysis_output, summary_blob)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/__init__.py", line 441, in run
    next_input, summary = step.run(next_input, summary)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/base_parser.py", line 251, in run
    self.analysis_output_to_dict_entries(
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/base_parser.py", line 203, in analysis_output_to_dict_entries
    for typ, key, e in self._analysis_output_to_parsed_tuples(inputfile):
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/base_parser.py", line 141, in _analysis_output_to_parsed_tuples
    for e in entries:
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/mariana_trench_parser.py", line 338, in parse
    yield from self.parse_handle(handle)
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/mariana_trench_parser.py", line 348, in parse_handle
    for precondition in self._parse_precondition(model):
  File "/Users/listennter/.venvs/dev-mariana/lib/python3.9/site-packages/sapp/pipeline/mariana_trench_parser.py", line 448, in _parse_precondition
    caller = Method.from_json(model["method"])
KeyError: 'method'
```

### What Cause this Problem

When mariana find an issue which source/sink is an "Field". It will contain an json like this in its output

```JSON
      {
        "field": "Lcom/unicom/xiaowo/account/shield/e/g;.d:Ljava/lang/String;",
        "position": {},
        "sinks": [
            {
                "callee_port": "Leaf",
                "field_callee": "Lcom/unicom/xiaowo/account/shield/e/g;.d:Ljava/lang/String;",
                "field_origins": [
                    "Lcom/unicom/xiaowo/account/shield/e/g;.d:Ljava/lang/String;"
                ],
                "kind": "N1rv0us-sink"
            }
        ],
        "sources": [
            {
                "callee_port": "Leaf",
                "field_callee": "Lcom/unicom/xiaowo/account/shield/e/g;.d:Ljava/lang/String;",
                "field_origins": [
                    "Lcom/unicom/xiaowo/account/shield/e/g;.d:Ljava/lang/String;"
                ],
                "kind": "SSID"
            }
        ],
        "line": 9805
    }
```
but when sapp pasing precondition/postcondition,  It will assume that all results are method,thus ignoring the parsing of field.
some code in sapp/pipeline/mariana_trench_parser.py
https://github.com/facebook/sapp/blob/main/sapp/pipeline/mariana_trench_parser.py

```python
    def _parse_precondition(self, model: Dict[str, Any]) -> Iterable[Precondition]:
        caller = Method.from_json(model["method"])
        caller_position = Position.from_json(model["position"], caller)
        ...

    def _parse_postconditions(self, model: Dict[str, Any]) -> Iterable[Postcondition]:
        caller = Method.from_json(model["method"])
        caller_position = Position.from_json(model["position"], caller)
        ... 
```

### How to Fix
Hope to support the parsing of Field results soon.

**Comment by N1rv0us** [comment]
I try to update sapp with :

```
$ pip install fb-sapp==0.5.2
```

and I found this issue is already fixed.
