### ISSUE TITLE
KeyError: 'port' when following mariana-trench guide

### ISSUE THREAD

**Issue by a-huk** [facebook/sapp#88]
https://github.com/facebook/sapp/blob/e6f541a3a35498f75cbf4eb7d672576721731785/sapp/pipeline/mariana_trench_parser.py#L850

I am trying to make mariana-trench work and have followed their guide on there repo (https://github.com/facebook/mariana-trench). Everything seems to run successfully but when I want to use sapp to analyse, I get "KeyError: 'port'". Here is the full error:
`/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py:1994: SAWarning: Setting backref / back_populates on relationship Run.issue_instances to refer to viewonly relationship IssueInstance.run should include sync_backref=False set on the Run.issue_instances relationship.  (this warning may be suppressed after 10 occurrences)
  util.warn_limited(
/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py:1994: SAWarning: Setting backref / back_populates on relationship IssueInstance.run to refer to viewonly relationship Run.issue_instances should include sync_backref=False set on the IssueInstance.run relationship.  (this warning may be suppressed after 10 occurrences)
  util.warn_limited(
2023-02-06 00:03:09,854 [INFO] Parsing analysis output...
Traceback (most recent call last):
  File "/home/hukad/.venvs/mariana-trench/bin/sapp", line 33, in <module>
    sys.exit(load_entry_point('fb-sapp==0.5.4', 'console_scripts', 'sapp')())
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/cli_lib.py", line 206, in analyze
    pipeline.run(analysis_output, summary_blob)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/__init__.py", line 365, in run
    next_input, summary = step.run(next_input, summary)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/base_parser.py", line 231, in run
    self.analysis_output_to_dict_entries(
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/base_parser.py", line 183, in analysis_output_to_dict_entries
    for typ, key, e in self._analysis_output_to_parsed_tuples(inputfile):
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/base_parser.py", line 132, in _analysis_output_to_parsed_tuples
    for e in entries:
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/mariana_trench_parser.py", line 541, in parse
    yield from self.parse_handle(handle)
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/mariana_trench_parser.py", line 555, in parse_handle
    for precondition in self._parse_preconditions(model):
  File "/home/hukad/.venvs/mariana-trench/lib/python3.10/site-packages/sapp/pipeline/mariana_trench_parser.py", line 850, in _parse_condition
    port=Port.from_json(leaf_model["port"], leaf_kind),
KeyError: 'port'`

This happens both when installing fb-sapp from pip or directly from github.

**Comment by a-huk** [comment]
I would assume that it has something to do with this:
`ERROR Model Consistency Error: Model for method`

**Comment by sinancepel** [comment]
Hey, could you share the exact commands you used to be able to repro the issue? Additionally, could you share the version of Mariana Trench you were running on? Asking to ensure I can repro the exact issue. You can get the Mariana Trench version by running `mariana-trench --version` =)

**Comment by sinancepel** [comment]
I don't think the `sapp --version` command exists, however the stack trace indicates that they're using a very recent version of `sapp` (since it's called `mariana_trench_parser.py` instead of `mariana_trench_parser_v2.py`).

**Comment by a-huk** [comment]
> Hey, could you share the exact commands you used to be able to repro the issue? Additionally, could you share the version of Mariana Trench you were running on? Asking to ensure I can repro the exact issue. You can get the Mariana Trench version by running `mariana-trench --version` =)

mariana-trench 1.0.2, which seems to be the latest from pip. 

> Please also provide the fb-sapp version :)



> I don't think the `sapp --version` command exists, however the stack trace indicates that they're using a very recent version of `sapp` (since it's called `mariana_trench_parser.py` instead of `mariana_trench_parser_v2.py`).

Indeed the --version command does not exist for sapp, but it should be new as I installed it via pip directly from github, I would say maximum a weekend old.

The command used was the same as on the guide of mariana-trench: `sapp --tool=mariana-trench analyze .`
It seems to be specific to the apk/app that you analyze as with some apps it works, but for the "demo" one on the mariana-trench repo it seems to give the observed behaviour above.

**Comment by sinancepel** [comment]
@a-huk I was able to repro the issue on the same version, with a similar pip checkout. Building the latest Mariana Trench version from source made the issue go away, so I'll see if I can cut an open source release here!

**Comment by sinancepel** [comment]
@a-huk Mariana Trench 1.0.3 is out for Linux and Mac OS X - would appreciate if you could give that a spin, and let me know if the issues persist. Closing for now, feel free to re-open if it doesn't get addressed.
